config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: "home"
  get 'about' => 'pages#about'

  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name:'admin', password:'123'

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Страница про нас'
    @text = 'Дополнительный текст о нас'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name:'admin', password:'123', except: [:index, :show]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
     redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-bold">Simple project</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark" ><%= link_to "Главная", home_path %></span>
      <span class="p-2 text-dark" ><%= link_to "О нас", about_path %></span>

    </nav>
    <span class="p-2 text-dark" ><%= link_to "Новый пост", new_post_path %></span>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>

<p><%= @text %></p>

app/views/posts/edit.html.erb
<h2>Редактирование нового поста</h2>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg|%>
      <div class="alert alert-danger"><%=msg %></div>
    <% end %>
  <%end %>


  <p>
    Название<br>
    <%=f.text_field(:title, {:class=>'form-control'}) %>
  </p>
  <p>
    Текст статьи<br>
    <%=f.text_area(:body, {:class=>'form-control'}) %>
  </p>
  <p>

    <%=f.submit({:class=>'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Все посты</h1>
<% @posts.each do |post|%>
  <div class="well">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Читать далее", post_path(post), :class=>'btn btn-outline-primary' %>
  </div>
  <br>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>

<%= form_for :post, url: posts_path do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg|%>
      <div class="alert alert-danger"><%=msg %></div>
    <% end %>
  <%end %>


  <p>
    Название<br>
    <%=f.text_field(:title, {:class=>'form-control'}) %>
  </p>
  <p>
    Текст статьи<br>
    <%=f.text_area(:body, {:class=>'form-control'}) %>
  </p>
  <p>

    <%=f.submit({:class=>'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class=>'btn btn-warning' %>
<%= link_to "Удалить", post_path(@post), method: :delete, data: {confirm: "Хотите удалить статью?"}, :class=>'btn btn-danger' %>

<hr>
<h2>Все комментарии</h2>
<% @post.comments.each do |comment|%>
  <div class="alert alert-light">

    <p><strong><%= comment.username %></strong> <%= comment.body %></p>
  </div>
<% end %>

<hr>

<h2>Добавление комментария</h2>

<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    Пользователь<br>
    <%=f.text_field(:username, {:class=>'form-control'}) %>
  </p>
  <p>
    Текст комментария<br>
    <%=f.text_area(:body, {:class=>'form-control'}) %>
  </p>
  <p>

    <%=f.submit('Добавить комментарий',{:class=>'btn btn-warning'}) %>
  </p>
<% end %>